import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the filesystem, or explicitly defined here
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],
  roadmapSidebar: [
    'roadmap/index',
    {
      type: 'category',
      label: '開発環境構築',
      link: {
        type: 'doc',
        id: 'roadmap/dev-environment/index',
      },
      items: [
        'roadmap/dev-environment/monorepo',
        'roadmap/dev-environment/docs-setup',
        'roadmap/dev-environment/config-setup',
        'roadmap/dev-environment/git-hooks',
        'roadmap/dev-environment/test-environment',
      ],
    },
    'roadmap/ai-environment',
    'roadmap/clean-architecture-ddd',
    'roadmap/aws-environment',
    'roadmap/monitoring-environment',
  ],
};

export default sidebars;
